{
 "title": "Admin-User-Activity",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "username",
    "label": "username",
    "query": {
     "query": "kube_namespace_created{exported_namespace=~\"user-.*\"}"
    }
   },
   {
    "name": "instanceType",
    "query": {
     "query": "label_values(kube_pod_container_info{exported_namespace=~\"user-.*\"} ,container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "User Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User Auth Activity",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(keycloak_registered_events_by_user{user=~\".*\"}[15d])"
    }
   ]
  },
  {
   "title": "User Auth Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(keycloak_registered_events_by_user[15d])) by (user)"
    }
   ]
  },
  { "title": "Instance Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Intance's CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"user-.*\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Instance Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"user-.*\",interface=\"eth0\"}[5m])) by (pod)"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"user-.*\",interface=\"eth0\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Instance-Activity",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "\n(\n  (sum (kube_ingress_created{exported_namespace=~\"user-.*\"}) by (ingress) - sum (kube_ingress_created{exported_namespace=~\"user-.*\"}) by (ingress))\n)\n+ on(ingress)\n(\nsum(\n    rate(nginx_ingress_controller_requests{exported_namespace=~\"user-.*\"}[15d]))\nby (ingress)\n)\nor on(ingress)\n(\n  (sum (kube_ingress_created{exported_namespace=~\"user-.*\"}) by (ingress) - sum (kube_ingress_created{exported_namespace=~\"user-.*\"}) by (ingress))\n)"
    }
   ]
  },
  {
   "title": "Instance Accesses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "(\n  (sum (kube_ingress_created{exported_namespace=~\"user-.*\"}) by (ingress) - sum (kube_ingress_created{exported_namespace=~\"user-.*\"}) by (ingress))\n)\n+ on(ingress)\n(\nsum(\n    rate(nginx_ingress_controller_requests{exported_namespace=~\"user-.*\"}[15d]))\nby (ingress)\n)\nor on(ingress)\n(\n  (sum (kube_ingress_created{exported_namespace=~\"user-.*\"}) by (ingress) - sum (kube_ingress_created{exported_namespace=~\"user-.*\"}) by (ingress))\n)"
    }
   ]
  }
 ]
}